# This example didn't have much effort put into it. If you're running retroarch, you should probably
# Be using graphics acceleration. Don't use pixman to render it unless you hate your CPU.

version: "3"

services:
  sway:
    image: ghcr.io/pod-arcade/sway
    environment:
      - DISABLE_HW_ACCEL=true
      - WLR_RENDERER=pixman
      - WLR_BACKENDS=headless
      - RESOLUTION=1920x1080
    ports:
      - "6900:5900"
      - "7900:7900"
    privileged: true
    volumes:
      - shared_pulse:/tmp/pulse
      - shared_sway:/tmp/sway
      - shared_x11:/tmp/.X11-unix

  retroarch:
    build: ./
    restart: on-failure
    links:
      - sway
    depends_on:
      - sway
    environment:
      - WAYLAND_DISPLAY=wayland-1
      - DISPLAY=:0
      - XDG_RUNTIME_DIR=/tmp/sway
      - PULSE_SERVER=unix:/tmp/pulse
    volumes:
      - shared_pulse:/tmp/pulse
      - shared_sway:/tmp/sway
      - shared_x11:/tmp/.X11-unix
    user: "1000"
    command:
      - "sh"
      - "-c"
      - |
        sleep 5 # Wait for sway to start
        retroarch --verbose
volumes:
  shared_pulse:
  shared_sway:
  shared_x11:
